### ISSUE TITLE
Adjust repository description

### ISSUE THREAD

**Issue by gregorymartin** [dlarrick/hass-kumo#10]
The repository description gets pulled in by HACS and incorrectly references KumoJS currently. 

![007B4CAB-B5C9-47D2-9223-EA4CC1ABB776](https://user-images.githubusercontent.com/1591110/71783820-f894de00-2fa0-11ea-80bf-9e894292157d.jpeg)

**Comment by dlarrick** [comment]
Good catch. Done. We'll see if it takes an update to refresh.

**Comment by dlarrick** [comment]
Seems fine now. Closing.
