### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by matthewhadley** [dlarrick/hass-kumo#101]
From the Home Assistant logs in version `2023.2`

> Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for kumo using this method at custom_components/kumo/__init__.py, line 102: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by bmos** [comment]
It's right [here](https://github.com/dlarrick/hass-kumo/blob/854423af15cf3cd41c8ebd24de5f29d1ddcfda61/custom_components/kumo/__init__.py#L102).

**Comment by dlarrick** [comment]
Thanks, I should have time to fix this up this week
