### ISSUE TITLE
Any way to update "prefer cache," short of reinstalling?

### ISSUE THREAD

**Issue by bdimaggio** [dlarrick/hass-kumo#116]
Don't mind doing that if necessary, but I'm pretty sure this is just a matter of changing a yaml file. If so, can anybody tell me which one, and where exactly? Thanks!

**Comment by dlarrick** [comment]
There isn't a way to do this thru the GUI. See #94 . Patches welcome :-)

The value is stored in `.storage/core.config_entries` . To successfully edit this file, shut down your HA first, and restart it when done editing. Don't mess up the syntax, or your HA won't start up.

**Comment by bdimaggio** [comment]
Thanks, @dlarrick ! Will look into providing that patch.
