### ISSUE TITLE
Custom IP address not working

### ISSUE THREAD

**Issue by bgalbs** [dlarrick/hass-kumo#117]
My Mitsubishi mini-split A/C unit had its IP address change. However, for some reason the integration persists in using the old IP address.

I have deleted the configuration and recreated it; I have deleted the Kumo HACS installation add-on and reinstalled it. In both cases, the IP address that I presume the Kumo Cloud service is returning (192.168.1.46) is being used, whereas the unit itself has 192.168.1.47. I have set the IP address as 192.168.1.47 via the config override is the integration, and set it to prefer the local cache, but in both cases, it persists in searching for the A/C unit at 192.168.1.46.

Interestingly, the Kumo app on my iPhone works fine; it is communicating with the A/C unit at 192.168.1.47, too.

**Comment by omriasta** [comment]
You need to remove the kumo_cache.json file in your home assistant config folder.

**Comment by bgalbs** [comment]
Fixed it, thanks!
