### ISSUE TITLE
Lots of new errors in Hassio Log

### ISSUE THREAD

**Issue by omriasta** [dlarrick/hass-kumo#13]
Timeout issuing request http://x.x.x.x/api: HTTPConnectionPool(host='x.x.x.x', port=80): Max retries exceeded with url: /api?m=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9369511650>, 'Connection to x.x.x.x timed out. (connect timeout=0.2)'))

**Comment by omriasta** [comment]
I assume this has to do with the timeout that you added. Everything still works, just getting a lot of messages in the log for this component...
Also getting:
Error retrieving sensors

**Comment by dlarrick** [comment]
That's what those messages mean all right. I would have thought 200 msec (connect) / 5 seconds (response) was enough. But clearly not.

There *is* a possibility this issue could cause it to miss a command (not just a status update) so I will try to find time to fix this soon.

**Comment by dlarrick** [comment]
All right, I've pushed a fix for this. I increased the default timeouts and also added re-tries. The timeouts are now configurable as well; add something like:
```
  connect_timeout: 1.0
  response_timeout: 10.0
```
to your kumo section of your config

**Comment by omriasta** [comment]
OK, updated and added the config. I'll keep you posted if I see anything

**Comment by omriasta** [comment]
Still got one error:
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9f4b8e23d0>, 'Connection to x.x.x.x timed out. (connect timeout=1.0)')': /api?m=XXXXXXXXXXXXXXX

**Comment by dlarrick** [comment]
That one is the retry kicking in (and succeeding, if you don't see another error after it). It couldn't connect to your indoor unit in one second (!). I'm not sure if I can suppress this message or not.

**Comment by omriasta** [comment]
No problem, that's the only one I saw and it seems fine. Wasn't sure if I should change the timeout settings...

**Comment by dlarrick** [comment]
I'm going to close this issue since the timeouts are adjustable now -- you could even set a really high timeout to totally eliminate any such messages (though I wouldn't recommend it)
