### ISSUE TITLE
Over-specified ClimateEntityFeature HVACMode(s)

### ISSUE THREAD

**Issue by bmos** [dlarrick/hass-kumo#137]
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate (documentation, issues)
First occurred: 9:33:20 AM (1 occurrences)
Last logged: 9:33:20 AM

Entity None (<class 'custom_components.kumo.climate.KumoThermostat'>) implements HVACMode(s): off, cool, dry, heat, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/dlarrick/hass-kumo/issues

I think this relates to #130

**Comment by bmos** [comment]
I think this will be resolved by https://github.com/dlarrick/hass-kumo/pull/155

**Comment by mhollerb** [comment]
@bmos 
I recently had a Kumo unit installed and get the same '...ClimateEntityFeature...' error with a note to submit a bug report. Sounds like this may soon be resolved this, but do you still want a bug report?

Thanks.

**Comment by bryanyork** [comment]
I now get entity does not support this service. Is this expected? I am on the latest version. I can longer turn off my Kumo's via Google.

**Comment by bryanyork** [comment]
Changing _enable_turn_on_off_backwards_compatibility to True got things working again.

**Comment by bryanyork** [comment]
Looks like we need to enable ClimateEntityFeature.TURN_OFF now. I can submit a PR if needed

**Comment by bmos** [comment]
I am able to turn mine off and on via HA.

**Comment by bryanyork** [comment]
@bmos the issue is turning off via Google Assistant which expects to issue a climate.turn_off service call to the entity. I could also turn off directly from Home Assistant.

**Comment by bmos** [comment]
Ah, got it. So perhaps the issue is with the Google Assistant integration?
Because if you re-add this then it will cause a deprecation warning again I think
