### ISSUE TITLE
No Kumo discovery. The following integrations and platforms could not be set up:  kumo.climate kumo.sensor

### ISSUE THREAD

**Issue by jtrpop** [dlarrick/hass-kumo#141]
Some help if you please as I can’t get my Mitsubishi heat pump to show up.

-Statically assigned IP, can see & control it in the Kumo Cloud app, even Alexa’s plugin works, so we know the adapter is up on and accessible. Installed from HACS, but here is where I get stuck and never see the device or entity:

When prompted, enter your KumoCloud username (email address) and password. **<<Entered**
You can also enable the prefer_cache setting in this dialog. See details below. **<<did this, but notice it never sets the “address”: “192.168.0.127”, in the kumo_cache.json, but even when I do I still don’t get my device to show up.**
Click Submit to enable the integration and begin device discovery. **<< I submit, it says success, I click finish, but now begin discovery? What discovery?**
Once discovery is complete: **<<What discovery? I’ve waited, rebooted, reinstalled, and don’t see a device, entity, or climate entry at all. I don’t get any of these prompts the instructions say I will.**
You’ll be prompted to assign a room (Area in Home Assistant terminology) for all discovered devices. **<< Nope, wasn’t prompted.**
You might be prompted to assign IP addresses for devices where Kumo didn’t receive an IP address from the KumoCloud service. See details below. **<<Nope, wasn’t prompted, but as mentioned in #2 I did add this and no difference.**
In notifications I did get an Invalid Config for kumo.climate and kumo.sensor. Log shows this:
Logger: homeassistant.setup
Source: setup.py:291
First occurred: 10:57:38 PM (2 occurrences)
Last logged: 10:57:38 PM

Unable to prepare setup for platform kumo.climate: Platform not found (cannot import name ‘HVACAction’ from ‘homeassistant.components.climate.const’ (/usr/src/homeassistant/homeassistant/components/climate/const.py)).
Unable to prepare setup for platform kumo.sensor: Platform not found (cannot import name ‘UnitOfTemperature’ from ‘homeassistant.const’ (/usr/src/homeassistant/homeassistant/const.py)).

Any help would be greatly appreciated. Thanks.

**Comment by dlarrick** [comment]
This type of question is better asked over at the Home Assistant forum.

That said: if you're not given the opportunity to supply the IP address in the setup flow, you can:
- Shut down Home Assistant
- Add the IP in the proper location in kumo_cache.json ("prefer cache" must be in use)
- Restart Home Assistant

OTOH I see some issues with "HVACAction" etc. in the log you shared. What HomeAssistant version are you running? There were some recent changes to switch to these newer types, that may require a fairly recent (within the last few months) HA version.

**Comment by jtrpop** [comment]
Posted in Home Assistant forum, no response. Already did all the bullet points mentioned, no change. Running Home Assistant 2021.12.10

**Comment by omriasta** [comment]
The old version is most likely the issue. You can try to grab an older version of the integration from HACS which may work better but the most recent was updated with a few requirements from the newer versions of HomeAssistant as they have deprecated many functions.

**Comment by jtrpop** [comment]
I manually installed version 2.8 as that was released around the time of the Home Assistant version I have and it works. Thank you. I do have reasons for running the old version and do hope to upgrade when I have time. Thanks for the integration.
