### ISSUE TITLE
Deprecated HomeAssistantType

### ISSUE THREAD

**Issue by jftanner** [dlarrick/hass-kumo#144]
Hello,

I noticed this in my logs while investigating something totally unrelated, and figured I should report it as instructed.

> Logger: homeassistant.helpers.typing
> Source: helpers/deprecation.py:206
> First occurred: 10:26:09 PM (3 occurrences)
> Last logged: 10:26:30 PM
> 
> HomeAssistantType was used from kumo, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'kumo' custom integration

Hopefully this is an easy fix.

Thanks!

**Comment by dlarrick** [comment]
Thanks, will fix at some point.
