### ISSUE TITLE
async_forward_entry_setup is called during setup and is deprecated

### ISSUE THREAD

**Issue by bmos** [dlarrick/hass-kumo#152]
Core 2024.7.1
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240705.0

> Detected code that calls async_forward_entry_setup for integration kumo with title: [redacted] and entry_id: fb63f902e6f7d9f31857d858778b9026, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by barndawgie** [comment]
I think it must be referring to this call: https://github.com/dlarrick/hass-kumo/blob/dd9b9d1b136f92442608e76e8687017c34d8a845/custom_components/kumo/__init__.py#L104

I don't have enough familiarity with the async setup to say how this is supposed to work.

**Comment by bmos** [comment]
I think it's saying that line just needs to start with `await`
But I'm not sure.
