### ISSUE TITLE
upgrade to homeassistant 109

### ISSUE THREAD

**Issue by omriasta** [dlarrick/hass-kumo#16]
The following error shows up after upgrade to homeassistant 109:
`Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kumo doing I/O at custom_components/kumo/climate.py, line 116: self._pykumo = pykumo.PyKumo(name, address, config_js, timeouts=timeouts)`

**Comment by dlarrick** [comment]
I won't get a chance to look at this until the weekend. It should only appear at startup, and isn't hurting anything (until HA turns it into an error, of course). But it should get fixed.

**Comment by omriasta** [comment]
Thanks for quick response! As always if you need testing let me know.

**Comment by dlarrick** [comment]
Released; you should see the update in HACS @omriasta

**Comment by omriasta** [comment]
Got it, works great, Thanks!
