### ISSUE TITLE
Kumo setup can't find IP addresses

### ISSUE THREAD

**Issue by adarsh** [dlarrick/hass-kumo#168]
Everything seems fine when setting up but I get this message:

```
Kumo failed to return an IP address. For the following units, please replace the text with their local IP addresses
```
And an image of three form fields with the 3 unit names and IP or MAC addresses, like `50:26:ef:5f:67:b8`.

Maybe I'm missing something but how do I find the local IP addresses of my units?

**Comment by sinemaker** [comment]
Write down the MAC addresses.  Then go to your router DHCP list (ip address list) and locate each of these MAC addresses.  There you should be able to locate the ip addresses that have been assigned to each device by your router.

While communicating with your router you should figure out how to make these static ip addresses (that never change).  With a static ip address you can select local_cache when setting up the Kumo Cloud integration in HA which allows HA to control your HP's even if the Kumo Cloud server is not available (like internet down but LAN still working).

If the static ip address is the same as what it was earlier you don't need to do more.  In my case static ip addresses have to be in a different range than the ones that are dynamically assigned, so the new static ip's are different.  If your static ip is different from the one the router assigned earlier you will need to power your HP off then back on to grab the new ip address.

**Comment by dlarrick** [comment]
Copying what I just wrote on a similar ticket:

Yeah, this is a common problem. It takes some time for KumoCloud service to actually have the IP address of newly installed indoor units.

A few things:

Make sure "prefer cache" is selected at install time
It's highly recommended to use an assigned IP address for your indoor units (in your router or whatever is handling DHCP on your network)
See https://github.com/dlarrick/hass-kumo?tab=readme-ov-file#ip-addresses for some tips, including a potential way to get KumoCloud to refresh its info
If you're prompted for IP addresses at install time, you should have them from bullet 2 here.

**Comment by adarsh** [comment]
Ok amazing. I got it to work finally. I proposed a patch to the README https://github.com/dlarrick/hass-kumo/pull/170

**Comment by dlarrick** [comment]
I adopted some of your text and updated the README.
