### ISSUE TITLE
Entities for newly installed heat pumps unavailable.

### ISSUE THREAD

**Issue by sinemaker** [dlarrick/hass-kumo#169]
I have had four Mitsubishi minisplits with Kumo Cloud for several years and have used this integration with HA to control them and log their parameters.

Two weeks ago I had two more minisplits installed, and a couple of days ago the technician returned to install the WiFi boards for Kumo Cloud connectivity.  After several attempts he was able to connect the new units to the Kumo iphone app -- but, we could not use the app on my iphone 8 (running IOS 16.7.10) but were able to use my wife's iphone13 and my newer ipad (Ipad OS 18.0).  Note that after the two new units were connected to Kumo cloud I could control them with either my ipad or my wife's phone -- but they do not show up at all on the Kumo app on my iphone 8.

The next day I added these new heat pumps to the Kumo Cloud integration on HA.  It took a few attempts, and eventually I just deleted the integration altogether and added it anew.  In doing so it automatically located my four older heat pumps but asked me to provide ip addresses for the two new ones -- which I did.  It then prompted me to assign the areas for all six heat pumps.  I now have six heat pumps that show up on my HA.  But all the entities for the two new heat pumps (Bed1 and Bed2) are unavailable.  In the main log I get this error.

This error originated from a custom integration.

Logger: custom_components.kumo.coordinator
Source: helpers/update_coordinator.py:386
integration: Kumo (documentation, issues)
First occurred: 7:36:11 AM (2 occurrences)
Last logged: 7:36:12 AM

Error fetching kumo_3734P008K100441F data: Failed to update Kumo device: Bed2
Error fetching kumo_3934P008D100124F data: Failed to update Kumo device: Bed1

It appears that all six heat pumps are using the same WiFi controller model PAC-USWHS002-WF-2 with the same firmware revision, 02.06.12.
I can control all six heat pumps with the phone Kumo Cloud app on my ipad or wife's iphone-13 but whenever I launch the Kumo App on my older iphone-8 I get a message "This device is offline. Kumo cloud features limited."  When I close the message window on my iphone Kumo cloud runs as it did before but showing only my older four heat pumps -- nothing for the new ones.
I have tried reloading HA, rebooting the HA server, etc. with no change.  

Sorry for the long detailed message -- but the problems with the app seem to me to be related to the HA problems.
At this time I have the latest HA core 16.10.1 and so far as I know the Kumo Cloud integration is up to date.

I did view the kumo_cloud.json file in studio code server and located lines for all six heat pumps including their correct ip addresses.

Thanks for any support.
John Scofield

**Comment by dlarrick** [comment]
Yeah, this is a common problem. It takes some time for KumoCloud service to actually have the IP address of newly installed indoor units.

A few things:
1. Make sure "prefer cache" is selected at install time
2. It's highly recommended to use an assigned IP address for your indoor units (in your router or whatever is handling DHCP on your network)
3. See https://github.com/dlarrick/hass-kumo?tab=readme-ov-file#ip-addresses for some tips, including a potential way to get KumoCloud to refresh its info
4. If you're prompted for IP addresses at install time, you should have them from bullet 2 here.

**Comment by sinemaker** [comment]
Problem has been solved.  It was a self-inflicted wound!  I had the two ip addresses for the new installs backward!  I am so sorry to have wasted your (and my) time.

All six heat pumps are now communicating correctly with HA.
