### ISSUE TITLE
Units switch to Cool when specifically set to Heat

### ISSUE THREAD

**Issue by hansw1204** [dlarrick/hass-kumo#171]
Ever since I started to try to heat my rooms this year, the unit I turn on in HA to Heat (whether manually or via automation) will switch itself to Cool after a while. I am not sure this is a HA problem or a Kumo problem but does anyone have an idea how to fix this?
Many thanks!

**Comment by dlarrick** [comment]
The only time I've seen anything like this is if someone turns the unit on via the IR remote control. It seems to set the mode (and maybe other settings) that were in use the last time the remote was used.

**Comment by hansw1204** [comment]
Thank you! I believe you are correct. I have since turned on to heat each unit with the IR remote and then turned them off. Now they stay on Heat when I turn on from HomeKit or HA.

**Comment by dlarrick** [comment]
Closing this.
