### ISSUE TITLE
Log Warnings in HA 0.110

### ISSUE THREAD

**Issue by gregorymartin** [dlarrick/hass-kumo#22]
Hi there, I just checked my logs after the latest release and noticed these two error messages related to this component and wanted to make them aware.

`WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kumo doing I/O at custom_components/kumo/__init__.py, line 84: if account.try_setup():`

`WARNING (MainThread) [homeassistant.components.climate] ClimateDevice is deprecated, modify KumoThermostat to extend ClimateEntity`

**Comment by dlarrick** [comment]
My earlier fix for event-loop IO was insufficient. I'll need to make a change to pykumo, which I was hoping to avoid.

The latter is an easy fix.

I won't have a chance to look at these (which are not hurting anything in the meantime) until this weekend.

**Comment by gregorymartin** [comment]
No rush, I just wanted to get them on record.  Thanks for your work and happy to test for you!

**Comment by tmchow** [comment]
Yeah I'm having same issue and a ton of logging errors:

```
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kumo doing I/O at custom_components/kumo/climate.py, line 126: if self._pykumo.has_dry_mode():
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kumo doing I/O at custom_components/kumo/climate.py, line 128: if self._pykumo.has_heat_mode():
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kumo doing I/O at custom_components/kumo/climate.py, line 130: if self._pykumo.has_vent_mode():
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kumo doing I/O at custom_components/kumo/climate.py, line 132: if self._pykumo.has_auto_mode():
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kumo doing I/O at custom_components/kumo/climate.py, line 135: if self._pykumo.has_vane_direction():
```

**Comment by dlarrick** [comment]
Those messages aren't actually hurting anything, but I hope to have a look at fixing them this weekend.

**Comment by dlarrick** [comment]
Fixed
