### ISSUE TITLE
Can't Configure via HA UI

### ISSUE THREAD

**Issue by barndawgie** [dlarrick/hass-kumo#31]
Despite your README indicating that Kumo can be configured via the GUI, I am not able to do so.

I installed HACS and found and installed Kumo through its UI (the "Automatic Installation" mechanism from your documentation). Even after a restart, I was not able to add Kumo via the Configurations -> Integrations -> + menu.

I was able to add Kumo by updating my configurations.yaml per your examples, and it is working now, so I know that everything did get correctly downloaded/installed by HACS.

I'm running:
- Home Assistant 0.111.4
- HACS 1.1.1
- Kumo0.1.6

Kumo also doesn't show in my "Integrations" page within HomeAssistant (i.e. <server>/config/integrations).

**Comment by barndawgie** [comment]
Oh - or is GUI setup only available via the new Beta release?

**Comment by jhuang0** [comment]
Yeah. There are two devs working to make it UI configurable. The non-beta version supports configuration.yaml inputs only.

**Comment by dlarrick** [comment]
Exactly. The beta is for the purpose of trying out Config Flow. There are no other changes.

I'll keep this issue open for discussion of any problems that come up.

**Comment by dlarrick** [comment]
Config Flow is out of beta, released as v0.2.0
