### ISSUE TITLE
Add Support for "vertical" Vane Orientation

### ISSUE THREAD

**Issue by barndawgie** [dlarrick/hass-kumo#34]
Mitsubishi ceiling units support a `vertical` vane orientation, which appears to also be supported by kumojs (though not yet kumopy). Would be great to add this as it's the only one to keep the fan from blowing on me all night.

**Comment by dlarrick** [comment]
Huh, you're right. I totally missed "vertical" a year ago when I wrote pykumo. Should be trivial to add, but then of course both components need a new release.

If you are at all handy with code, you can add "vertical" into the list at https://github.com/dlarrick/pykumo/blob/master/pykumo/pykumo.py#L219  in your own copy of pykumo.py. It should just get picked up and work after HA restart.

If you're able to do that, please report back here how it goes.

**Comment by barndawgie** [comment]
That change did work on my home assistant install. I submitted a PR to pykumo: https://github.com/dlarrick/pykumo/pull/8

**Comment by dlarrick** [comment]
I've released v0.2.0 with this change and the Config Flow GUI.
