### ISSUE TITLE
Login credentials don't work

### ISSUE THREAD

**Issue by zacs** [dlarrick/hass-kumo#40]
Running HA 0.115 in a pretty vanilla docker container. 

I've tried adding via configuration.yaml and also via the UI. I've also changed both my login name and password on the Kumo Cloud service, and tried both methods again, but no love. The error when trying to add via config is pretty ambiguous: 

```
Logger: homeassistant.setup
Source: setup.py:138 
First occurred: 3:22:23 PM (1 occurrences) 
Last logged: 3:22:23 PM

Setup failed for kumo: Integration failed to initialize.
```

I crafted a request as defined in https://github.com/dlarrick/hass-kumo/blob/8e5a40b7f4c2ce393ad17c035e0a4171457c6db6/custom_components/kumo/kumo_cloud_setup.py#L20 manually, and got a 200 response with all the details of my setup, so I don't think there's any issues in Mitsu's auth. 

Let me know what else I might be able to do to debug.

**Comment by dlarrick** [comment]
You might get more help posting on the Kumo thread in the HomeAssistant forum.

It certainly sounds to me like your password is being mishandled. If you can narrow down *which* special character might break it, we might be able to figure out why. As far as I know the code isn't doing anything unusual with the password string so it's likely to be more of a general HA password-handling issue than something specific to the integration.

**Comment by zacs** [comment]
Thanks, I will cross-post there. I agree that I suspect HA is malforming the password. I did change to a purely alphanumeric and it didn't help, sadly.

**Comment by omriasta** [comment]
Another thing to check would be that you can ping the internal IP of the Kumo unit from the homeassistant machine. Several users including myself have seen issues with the Kumo unit randomly blocking communication from certain IP's/devices which may cause this. For me, restarting the entire network usually resolves this. I have not been able to pin it down, it may also be due to the wifi hardware (google wifi for me).

**Comment by zacs** [comment]
Quick update that I just can't wrap my head around. I followed @dlarrick advice on just trying to load the account in a Python shell, and even that doesn't work (so nothing is wrong with the HA plugin). 

```
>>> from pykumo import KumoCloudAccount
>>> account = KumoCloudAccount.Factory()
Kumo Cloud username: my.email@email.com
Password: xxxx
>>> account.try_setup()
False
```

The username and pass work to login to the Kumo app, and I've tried resetting the password to all alphanumeric, etc. Super bizarre. 

I can ping the device just fine on the network, I just can't get credentials to do anything with that. Ah well, I guess I'll try a factory reset, if that's even possible on the Kumo device.

**Comment by omriasta** [comment]
should be:

```
account = KumoCloudAccount(your_email@address.com, your_password)
account.try_setup()
```

**Comment by dlarrick** [comment]
The `Factory` method is for just what @zacs is trying, in that it will prompt interactively for username & password.

One question I have, what region are you in? Do you know what Kumo server the app talks to? This might be easier to determine by using the webapp as seen in https://github.com/dlarrick/hass-kumo/issues/55 and browser-based devtools to look at the network activity.

If as you said in the first message of this issue you can get a 200 with those same credentials, that's definitely odd and in your shoes I might try to work up the chain from your working manual request, making it look more & more like the actual code HA uses until it doesn't work anymore.

**Comment by zacs** [comment]
Thanks for the pointer to the new webapp. Just tried it out and everything works as expected, including the 200 on `getDeviceUpdates`. I did also notice that the `getInfrequentDeviceUpdates` has a `password` property, is that at all useful in communicating with the device?

I suppose it's time to start digging into pykumo code, thanks for the pointers!

![image](https://user-images.githubusercontent.com/27705/132748117-775fdffb-647b-4910-bc70-dee9b426b62d.png)

**Comment by danielgoepp** [comment]
@zacs this is probably stale at this point, okay to close this issue?

**Comment by zacs** [comment]
@danielgoepp Certainly. The issue persists but I will open a new issue when I get around to debugging what is going on.

**Comment by danielgoepp** [comment]
Neah, if you are still having the issue, I'm curious ;) I was just going through some tickets looking for some comments I had remembered, and I saw this one, related to the issues some folks had. When this thread started you were running an older version, I'm assuming you have upgraded HA since then, but the problem persists? Seems you had the auth issue, but then you posted you are getting a 200 okay. What is the current issue that persists? Is it consistent or just some of the time?

**Comment by zacs** [comment]
Yah, I'm fully up-to-date on the plugin, and on HA 2011.11.5. 

However, I will now eat crow, because I gave it another shot and it worked just fine. Couldn't find an IP so the nice setup UI asked me to enter that, but otherwise it appears to be working great. I'm guessing I must have upgraded but never tried re-adding since it had never worked before -- my bad! 

Thanks for motivating me to try again!

**Comment by danielgoepp** [comment]
Fantastic! I'm glad it's working for you now.

**Comment by zacs** [comment]
Ugh, I hate bringing this one back up. I recently got a second mini split, but the unit never showed in the integration. I thought perhaps deleting and re-adding would help. Unhappy surprise that now the `Invalid credentials, Wrong user or password` is all that comes up when I try to re-add the integration. 

I still get a 200 when I use curl, and I now get a `True` when testing in a Python shell: 

```
➜ python3.11           
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pykumo import KumoCloudAccount
>>> account = KumoCloudAccount.Factory()
Kumo Cloud username: zac.schellhardt@gmail.com
Password: 
>>> account.try_setup()
True
```

I'm running latest HA (2023.4.6) and have the latest version of this component installed. No special characters in the password. Any way for me to debug wtf is going on?

**Comment by zacs** [comment]
Very mixed results as I prod at it more, I am now getting this error from the shell. 

```
>>> account.try_setup()
True
>>> kumos = account.make_pykumos()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/pykumo/py_kumo_cloud_account.py", line 257, in make_pykumos
    kumos[name] = kumo_class(name, self.get_address(unitSerial),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pykumo/py_kumo.py", line 42, in __init__
    super().__init__(name, addr, cfg_json, timeouts, serial)
  File "/opt/homebrew/lib/python3.11/site-packages/pykumo/py_kumo_base.py", line 29, in __init__
    'password': base64.b64decode(cfg_json["password"]),
                                 ~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by zacs** [comment]
During the day I was getting `False` for `try_setup` but it now works again. I ran a `get_raw_json()` command in the console and got a huge dump of data. When I went to format it using a prettifier and I got several errors (presumably from bad JSON sent by kumo cloud itself:

- `Property keys must be doublequoted` with a fail on parsing since the whole blob uses single quotes
- Identifier 'None' is not allowed in JSON. This is due to the beginning of the JSON dump: `[{'token': 'foobar', 'username': 'my@email.com', 'device': None, 'emailIsVerified': False}, {'lastUpdate': 1593294157376, ...`

Is the `None` in the above something you've seen before? I am happy to send the full JSON dump, it is just a bit long.

**Comment by dlarrick** [comment]
Sorry to not be much help here. Just a couple general comments:

If it works sometimes and doesn't work other times, something is different. Maybe you're getting different results from the Kumo servers. Maybe you're doing something subtly different. 

Standard debugging advice applies: be methodical, take notes, verify your assumptions. In this case I'd probably be saving off the KumoCloud responses to files so I can diff them.

**Comment by zacs** [comment]
It looks like the problem is that `get_credentials()` doesn't return anything for my units ever. Neither does `get_address()` which seems fine, but weirdly `get_unit_type()` also returns nothing. Name, MAC return as expected. At this point I am assuming that the kumo cloud JSON is malformed and messing with the parsing assumptions in the library. @dlarrick is it normal for any of these methods to be empty (other than the address one)? 

```
>>> account.get_all_units()
dict_keys(['9934P008K100307F', '3134P008D100236F'])
>>> account.get_indoor_units()
['9934P008K100307F', '3134P008D100236F']
>>> account.get_unit_type('9934P008K100307F')
>>> account.get_credentials('9934P008K100307F')
>>> account.get_name('9934P008K100307F')
'Living Room'
>>> account.get_credentials('9934P008K100307F')
>>> account._fetch_if_needed()
>>> account.get_credentials('9934P008K100307F')
>>> creds = account.get_credentials('9934P008K100307F')
>>> print(creds)
None
>>> account.get_mac('9934P008K100307F')
'd4:53:83:2a:2e:1d'
>>> account.get_address('9934P008K100307F')
>>> account.get_address('3134P008D100236F')
>>> account.get_name('3134P008D100236F')
'Zac Office'
>>> account.get_mac('3134P008D100236F')
'24:cd:8d:17:27:1e'
>>> account.get_credentials('3134P008D100236F')
>>> account.is_indoor_unit('3134P008D100236F')
True
```

**Comment by zacs** [comment]
I tried about a million things here, and while it isn't totally deterministic, I believe what allowed me to add mine (again) was to have all units:

1. Powered on
2. Powered on for a significant (in my case it was overnight) amount of time

Totally doesn't make sense to me, but it ended up working.
