### ISSUE TITLE
Request for pull request into core

### ISSUE THREAD

**Issue by danielgoepp** [dlarrick/hass-kumo#41]
This is not technically an "issue" but I wasn't sure how else to communicate with the author here. I looked around to see if you have started the process of getting this merged into HA core, but didn't find anything. This looks like a great custom component, and I had no problem getting it setup. I'll play around more of course, but so far, it seems to work just fine. Do you have any plans to merge this into core? Great job, thanks for the work!

**Comment by dlarrick** [comment]
I currently have no such plans. My next priority for the component is improving behavior when an indoor unit is unreachable, but other priorities have kept me from having time for even that task.

That said, I have tried to follow HA guidelines as I understand them so it should eventually be possible to merge to core. If someone has the skills and time to work on that, I'd be happy to give my official blessing to such an effort.

**Comment by danielgoepp** [comment]
Thanks for the follow up. I have never gone through the process myself, however I am watching another project that is going through the process right now (Honeywell Home Lyric Integration). I'll read up and see if I can figure it out.
