### ISSUE TITLE
Setting set point temp incorrectly ignores hvac_mode

### ISSUE THREAD

**Issue by tmchow** [dlarrick/hass-kumo#43]
There are other HA integrations, like the scheduler card, that are calling set `hvac_mode` when the `set_temperature` service is called. However, that owner of that integration is saying this is "often ignored by integrations".

Source:
https://community.home-assistant.io/t/scheduler-card-custom-component/217458/951

For the scheduler card in particular, this prevents the actual mini split from turning on.  

Digging into a bit more, here is example of the JSON passed into the Kumo integration:

```
{
	'entity_id': ['climate.attic'],
	'hvac_mode': 'heat',
	'temperature': 21.666666666666668
}
```

**Comment by dlarrick** [comment]
v0.2.2-beta should fix this issue.
