### ISSUE TITLE
Occasional 'Unavailable' after upgrading to v0.2.3-beta2

### ISSUE THREAD

**Issue by jjhuff** [dlarrick/hass-kumo#45]
I was running v0.2.2 and it was rock solid (thanks!). I upgraded to v0.2.3-beta2 so I could pickup the set_temperature fix. Now, units randomly go unavailable. Happens to all of my units and it appears random.

Log msg:
Logger: pykumo.pykumo
Source: /usr/local/lib/python3.8/site-packages/pykumo/pykumo.py:109
First occurred: December 17, 2020, 12:01:58 PM (579 occurrences)
Last logged: 9:22:59 AM

Error retrieving status

**Comment by dlarrick** [comment]
Sadly, this issue likely indicates your HA indeed can't talk to the Kumo unit. I do see this in my own setup on occasion but not frequently. Next time you see it, try to ping the relevant indoor unit from the system where you run HomeAssistant. I'm guessing you'll see timeouts.

It's likely that with the old version, it was spamming your logs with connection failures but not actually reflecting the issue in the UI. I've been considering adding code to "ride out" a handful of consecutive failures, and to queue any commands that happen to come in while in this state. So I'll let this issue stand as a tracker for that possible development.

However, one thing you might want to do is check the WiFi signal strength at your indoor units (and at your Home Assistant host if it's on WiFi, which is probably a bad idea).

**Comment by jjhuff** [comment]
Ahh! Yes, I am seeing them occasionally drop of the network. Signal strength seems ok, but I might be getting interference (or they're shifting between APs. I did notice that the RTT is all over the map. 3ms to 200ms to all of the adapters, but the rest of the network seems fine and stable. Lovely :(

**Comment by dlarrick** [comment]
While it's admirable that Mitsubishi manages an embedded controller complete with WiFi for something around 1.5 watts (by my estimate), there are drawbacks. I think there are bugs in their TCP/IP implementation, and their WiFi radio is not very strong. There are things you can try:
* If you know how to get into the Installer Settings in the Kumo Cloud app there's a WiFi signal strength indication. In fact, I'm seeing that this info is available in the data HA gets from the indoor unit; I should add it as an attribute.
* Move the WiFi box around inside the indoor unit (on my units, it's inside an access panel on the bottom right-hand corner, right up against the wall; I can see its LEDs shining through the plastic if the room is dark). Rotation is probably more effective than linear translation unless there's something specific in the signal path. Making sure the cable is neatly stowed may help prevent it itself from blocking signals. 
* Switch to a dedicated SSID from the nearest AP if your router supports such a thing -- don't let it try to switch APs. See my note about the controller's feebleness.
* WiFi extender if all else fails

**Comment by dlarrick** [comment]
Well, that was pretty easy to get done. beta-0.2.4 implements both the things discussed here:
* signal strength indicator
* require 3 consecutive failures to declare "Unavailable". It's seen minimal testing, so please report any issues you see.

**Comment by jjhuff** [comment]
Hey! Just to close the loop on this. Wifi improvements have made it rock solid now.
