### ISSUE TITLE
entity is missing

### ISSUE THREAD

**Issue by soleen** [dlarrick/hass-kumo#46]
KUMO integration worked rock solid for a while, but I moved Home Assistant from virtual machine to a dedicated device, and now when I add Kumo integration the AC entity is missing.

Integration shows up and I can login into kumo cloud, but there are no entities after login. I have tried to remove integration, and remove Kumo from HACS. I also tried to delete kumo_cache.json, but still no AC entity.

Any suggestion?

**Comment by dlarrick** [comment]
If the entity is not showing up, it's either not represented properly in the kumo_cache.json (the data downloaded from the KumoCloud service), or it's not reachable from the HA server.

Look in your (new) kumo_cache.json . Is the unit there? Does it have an IP address? Can you ping that IP address from the HA server?

**Comment by soleen** [comment]
Thank you for suggestion. I checked kumo_cache.json and found that IP address of my AC is wrong. So, I manually changed it to the correct one, and now everything is working. I am not sure why KUMO integration kept getting a wrong address. I have modified my router to provde a static IP for my AC to avoid these problems in the future.

**Comment by dlarrick** [comment]
Ah. Yes, fixed IP is generally a good idea. It can take a while for the KumoCloud service to notice a new IP, and that's the only way we know what to talk to. Glad it's working for you again; I'm going to close this issue.
