### ISSUE TITLE
Unable to ping Wireless Controller from Inside HA

### ISSUE THREAD

**Issue by eBoon123** [dlarrick/hass-kumo#47]
Just moved my install from Ubuntu to a virtual machine on Proxmox. Everything is working perfectly except Kumo is unable to find my wireless unit. Did a bit of digging and found out that from inside of the new HA install on Proxmox, I am unable to ping my wireless unit. I am able to ping the unit without any issues at all directly from the Proxmox console (or anywhere else on my LAN). No issue pinging other devices from within HA.

I know this is NOT a Kumo issue, but wondering if anyone might have a clue what is going on.

*EDIT* NVM - Changed the IP address of the wireless unit and all is working again.

Please close

**Comment by dlarrick** [comment]
For others finding this through a search: I get the impression the TCP/IP stack on the wireless adapters is not, shall we say, fully RFC compliant. I think its arp tables get screwed up. In situations like this I have found rebooting the indoor unit and/or the router it's talking to can help.
