### ISSUE TITLE
Wrong IP addresses from API

### ISSUE THREAD

**Issue by nniehoff** [dlarrick/hass-kumo#48]
I have been having issues communicating with my units.  I think I have narrowed this down to their IP addresses have changed.  When I originally set them up they grabbed IPs from my large pool, I have since updated dhcp to assign different IPs to them.  The kumo app somehow still works but the API is returning the original IP addresses for the devices.  I have confirmed this by removing the kumo_cache.json and reinstalling the integration, the json still gets the original IPs.  I have tried updating the json locally but the integration is still trying the old IPs.  Is there a way to override the addresses in the configuration?

**Comment by dlarrick** [comment]
Nobody's been able to figure out how to convince the service there's a new IP address. Maybe it just takes time.

You can edit the kumo_cache.json file to insert the correct addresses. Make sure to set "prefer cache" if you do so.

You can also try clear-cache / force-quit of the Android app (or whatever the equivalent is on iOS) and re-open it. Make certain your phone is on the same WiFi as the units & HA.

**Comment by nniehoff** [comment]
@dlarrick Thanks yeah the service has a bit to be desired I got it working similar to the method described.  I'm excited to see if the home assistant integration is actually more reliable than the app using the correct IP.
