### ISSUE TITLE
Unable to add new device

### ISSUE THREAD

**Issue by nbanderso** [dlarrick/hass-kumo#49]
I installed a new mini-split and am unable to add it to my existing Kumo integration.  

I tried:

- reloading the integration
- disabling and re-enabling the integration
- deleting the integration and reinstalling it. 

No matter what I do, I can only access the existing units.

**Comment by dlarrick** [comment]
You're not the first with this issue. It takes some time (maybe even days) for the new unit to show up in the file we download from the KumoCloud service as kumo_cache.json , and/or for its IP address to appear there. We have no idea why. But if you're just missing the IP address, you can edit this file to add it as some of the other users have done.

I suggest you read thru some of the other issues here (open and closed) for some things to try, and/or ask for help over in the HA forum.

**Comment by dlarrick** [comment]
The beta released today would allow you to manually add the IP address if that being missing is what causes your issue (which is likely).

**Comment by danielgoepp** [comment]
@nbanderso are you still having this issue? Since the update that dlarrick mentions, I've not heard of any open issues on this front. Just curious if you were able to upgrade and if it resolved it for you.

**Comment by dlarrick** [comment]
Please see https://github.com/dlarrick/hass-kumo#ip-addresses in the README for some suggestions on how to get Kumo Cloud service to refresh itself.
