### ISSUE TITLE
Kumo fails to create entities for 2 mini-split heads

### ISSUE THREAD

**Issue by spurpura-edu** [dlarrick/hass-kumo#54]
Home Assistant 2021.7.2
Kumo release-0.2.5

Kumo has been added through HACS and flow configuration. After initial authentication success, a restart of Home Assistant failed to create the climate entities. Error message in the Home Assistant Log is below.

My system has 2 mini split heads. The root of the tree is named Home. The first unit is "Basement Bed". The second unit is "Media Room".

2021-07-14 21:57:44 ERROR (MainThread) [homeassistant.components.climate] Error while setting up kumo platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/kumo/climate.py", line 125, in async_setup_entry
kumo_api = pykumo.PyKumo(
File "/usr/local/lib/python3.9/site-packages/pykumo/pykumo.py", line 37, in __init__
'password': base64.b64decode(cfg_json["password"]),
TypeError: 'NoneType' object is not subscriptable

**Comment by spurpura-edu** [comment]
I blew away the Kumo configuration. Rebooted. Reinstalled from HACS. Rebooted. Installed the integration. Integration reported success. Saw this in the log: 

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/kumo/climate.py", line 128, in async_setup_entry
success = await hass.async_add_executor_job(kumo_api.update_status)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/pykumo/pykumo.py", line 103, in update_status
response = self._request(query)
File "/usr/local/lib/python3.9/site-packages/pykumo/pykumo.py", line 75, in _request
url = "http://" + self._address + "/api"
TypeError: can only concatenate str (not "NoneType") to str

**Comment by spurpura-edu** [comment]
Rebooted after installation. Saw this in the log:

2021-07-14 22:18:28 ERROR (MainThread) [homeassistant.components.climate] Error while setting up kumo platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/kumo/climate.py", line 125, in async_setup_entry
kumo_api = pykumo.PyKumo(
File "/usr/local/lib/python3.9/site-packages/pykumo/pykumo.py", line 37, in __init__
'password': base64.b64decode(cfg_json["password"]),
TypeError: 'NoneType' object is not subscriptable

**Comment by spurpura-edu** [comment]
I should have mentioned that this is a Raspberry Pi 4B install of Home Assistant OS. NUT is the only process that has been locally added.

**Comment by danielgoepp** [comment]
@spurpura-edu this sounds / looks like what was happening to me and others and was discussed in https://github.com/dlarrick/hass-kumo/issues/14 too if you want to read some of the details there. Basically, for whatever reason, the Kumo cloud service is not providing the IP addresses of your units in the response it gives. What I ended up doing was adding the integration, letting the kumo_cache.json file get generated, then manually adding the address. This happened for me after a power outage and some of my IP addresses changed. I have since setup reservations for my kumo units so they don't change. I looked up the units based on mac to be sure to set the correct address to the correct unit. I don't know how technical you are, and yes, this was a pain in the butt, but there is not real quick fix to this right now. I'm waiting to see if the service updates and starts providing IP addresses again, or a way to force it to, or why it seems to have stopped for some of us.

One quick way to check if this is your problem would be to see if your cache has addresses:

```
cat kumo_cache.json | egrep 'label|mac|address'
                        "mac": "dc:ef:ca:0a:e6:72",
                        "label": "Greatroom Kumo",
                        "address": "192.168.7.17",
                        "mac": "dc:ef:ca:10:25:dc",
                        "label": "Guestroom Kumo",
                        "address": "192.168.7.16",
                        "mac": "dc:ef:ca:10:8e:f0",
                        "label": "Bedroom Kumo",
                        "address": "192.168.7.15",
                        "mac": "dc:ef:ca:10:53:0b",
                        "label": "Studio A Kumo",
                        "address": "192.168.7.18",
```

If it doesn't you need to add them. I put mine right after the mac in the json file like this:

```
....
                "zoneTable": {
                    "**************": {
                        "serial": "**************",
                        "mac": "dc:ef:ca:0a:e6:72",
                        "label": "Greatroom Kumo",
                        "address": "192.168.7.17",
                        "port": 80,
....
```

I hope this helps.

**Comment by danielgoepp** [comment]
Oh, and one other thing, you need to set "prefer_cache" or it'll overwrite the kumo_cache.json with a new one from the service.

**Comment by danielgoepp** [comment]
@spurpura-edu sorry, I deleted my previous comment, I jumped to conclusions when I saw the last line of your error message :) I was getting the same NoneType error, but mine was due to a missing address field, not password. This looks like you either have no password set.

**Comment by dlarrick** [comment]
> 'password': base64.b64decode(cfg_json["password"]),
TypeError: 'NoneType' object is not subscriptable

Somehow the cfg_json is not present (is `NoneType`). I can only guess that perhaps your password contains special characters that are being misinterpreted by the code (not in Kumo or pykumo) that puts it into the config. Things like quotes or YAML comment characters (#) might be suspicious.

Or, as Daniel says, the "password" field is not present in your kumo_cache.json . If that's the case it's even more flakiness on KumoCloud service.

Can your KumoCloud app control the devices over WiFi?

**Comment by spurpura-edu** [comment]
My password is 43 characters long and contains alpha characters and periods. I have tested it with a 4 character password (“1234”) and the same behaviors appear.

Where is kumo_cache.json placed in the file system? I’ve been looking for it in /config/custom_components/kumo and I never see it.

I have ready access to KumoCloud through the app on an iPhone and through the web interface from a MacBook Pro. The web interface is really fast compared to the app, and I’m kinda thinking I will rarely use the app in the future.

I have a Ubiqitui Dream Machine Pro and the IP addresses of the mini-split heads did change after a power outage. I had marked them as DHCP Static addresses in the UDM interfaces, but that was not respected on restart and I still don’t know why. My Lutron Bridge also lost its IP address and it would not respect the UDM’s static IP info, so I had to manually change it a static IP address.

I also use a PiHole server with Unbound (recursive DNS) and I can see all of the queries being made to kumocloud by the mini splits and the Raspberry Pi running home assistant. 

I have nearly zero familiarity with Home Assistant (I’m only a few weeks into this journey) and I can do additional troubleshooting. I’m just still figuring out the architecture and tools available.

**Comment by dlarrick** [comment]
Please take this support discussion to the Home Assistant [discussion forum](https://community.home-assistant.io/t/mitsubishi-kumo-cloud-integration/121508). If you come up with a concrete action to improve the integration or underlying pykumo library, feel free to open another Issue here on GitHub. I'm going to close this one.
