### ISSUE TITLE
Timeout Values not using DataUpdateCoordinator

### ISSUE THREAD

**Issue by omriasta** [dlarrick/hass-kumo#66]
Wouldn't it be beneficial to let homeassistant set the times to update the entities using the DataUpdateCoordinator:
https://developers.home-assistant.io/docs/integration_fetching_data/

I don't see that implemented and wondering if this would also remove a lot of the log messages that we get when there is a timeout..maybe the 5 second update is a bit much for most entities?

**Comment by danielgoepp** [comment]
I haven't looked into this in detail, but at first glance seems like a good idea :) +1

**Comment by dlarrick** [comment]
Closing some old tickets. Kumo uses DataUpdateCoordinator as of the recent re-org.
