### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by mcnelson** [dlarrick/hass-kumo#73]
Hi, I'm not seeing Kumo Cloud in Home Assistant's integration list as it says it should be in the readme. I also tried cloning the repo directly into my HA installation, restarted the server, and it still didn't find it.

I'm surprised that nobody else has raised this. Am I overlooking something dumb? Or does the installation experience need some TLC?

**Comment by jhuang0** [comment]
This is not part of the official Home Assistant integration - you won't see it on the main HA Integrations webpage. It is part of the HACS store... so you'll want to go ahead and install that if you want it more tightly integrated with HA.

https://hacs.xyz/

**Comment by mcnelson** [comment]
Ah. My fault, sorry. I always thought HACS stood for HA cloud service. Didn't realize it was an aftermarket package manager. Thanks, will give it a try.
