### ISSUE TITLE
Issues with logging into the KUMO app with login credentials 

### ISSUE THREAD

**Issue by DAVFC294** [dlarrick/hass-kumo#75]
I am having issues with logging into the kumo hacs hass integration on initial setup - unable to authenticate. 

I am though able to login to the mobile app with no issues.

**Comment by jhuang0** [comment]
If you're the same guy who doesn't even have his equipment installed... maybe you should just wait until it's in before creating github issues without enough detail to troubleshoot.

**Comment by DAVFC294** [comment]
Thanks for the note: wasn’t sure it was connected to that the units are not in yet - we are trying to get everything pre-configured.

Configuration:
Utilize occupancy sensory to enable lights and turn unit on to predetermined setting for 2 hours and when there is no occupancy the unit will either raise or lower the temp


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pplevesque** [comment]
Hi there,

I had the same error and I replaced URL value from https://geo-c.kumocloud.com/login to https://app.kumocloud.com/login inside custom_components/kumo/kumo_cloud_setup.py and the GUI setup passed after restart.

**Comment by ehagan** [comment]
I don't know if this is related to the issue reported in here but I had a login issue. My password had two special characters in it, a period and a double quote. By changing those characters to numeric digits the login was able to proceed, e.g. abc.2" becomes abc123. If I had to guess I'd say it wasn't handling escaping or unescaping the double quote but that's just a guess without looking at code.

**Comment by dlarrick** [comment]
It looks like this is a defect in pykumo. See https://github.com/dlarrick/pykumo/blob/master/pykumo/py_kumo_cloud_account.py#L76-L77 ; it's sending the username and password as JSON. Since your special character is a double-quote, that would result in malformed JSON.

I've made a [ticket](https://github.com/dlarrick/pykumo/issues/29) for this in pykumo. This is a very simple one, if you (or anyone else reading) would like to take a stab at it and make a pull request.

**Comment by dlarrick** [comment]
Was fixed a while ago

**Comment by ChadHydro** [comment]
Just wanted to note that I recently encountered this issue on an install with the latest Home Assistant and hass-kumo and the only thing that fixed it was @pplevesque's suggestion

**Comment by dlarrick** [comment]
Thanks, I'm making a new Issue for this hostname problem.
