### ISSUE TITLE
Frequency of readings

### ISSUE THREAD

**Issue by TheGodMotherG** [dlarrick/hass-kumo#77]
Hello everyone great work on this absolutely life saving. I am using this application for a grow room where i have the pac-uswhs003-th-1 as a remote sensor. The humidity and the temps keep ranging pretty heavily because by the time the ac turns on starts working and it takes the next reading it overshot the cooling temp. 

Is there a way to make it read more frequently? 

or another ideas on how to get it to be more accurate?

Thanks

**Comment by dlarrick** [comment]
Home Assistant and the Kumo integration aren't involved at all in the control loop of the indoor unit. The code is just setting a temperature setpoint, and the indoor unit uses its internal operation to try to maintain that setpoint. The sensor readings are informational only. 

It sounds to me like your indoor unit is oversized for the area you're trying to control -- either that or the conditioned air is blowing directly on the sensor. Make sure the fan speed is as low as it will go to minimize the cooling power. Make sure the conditioned air is mixing properly with the room air and maybe add a baffle of some sort suspended in front of it. You could also try increasing the thermal mass in the room (big tanks of water, large stone or concrete blocks, etc.). But unless I'm misunderstanding what you're doing there's nothing to be done in code.

**Comment by TheGodMotherG** [comment]
at the moment it is a bit overpowered  but that is because the outside temp is very cold. I think for the rest of the year it will be good. Attached bellow are two pictures one from my sensor push(calibrated with visala HM40) bellow it is the PAC(kumo cloud wireless temp/humidity sensor). Where its circled the Mitsubishi held the temp exactly where I wanted for 90 minutes I wanted but it happens randomly. As far as air circulation i have 4 heavy duty large Vornado fans really moving the air around.

My question is is there a way to make the pac-uswhs003-th-1 through the code read every 15 or 30 seconds instead of the couple minute intervals it does now? This would drain the battery life faster but would significantly increase accuracy of the unit. The offset can be adjusted to make it accurate but the time in between readings handicaps the unit.

**Comment by dlarrick** [comment]
There's no such controls exposed through the indoor unit's API, no. Of course it's all reverse engineered so something could be hidden in there. As a long shot you might browse through the installer pages in the KumoCloud app (which is beyond the scope of this project but instructions for getting in there are online).

**Comment by TheGodMotherG** [comment]
Thanks for the help and the explanation I really appreciate it  I tried to google it but only the manual from Mitsubishi is coming up not sure if that's what you meant but its not in there. IF you could point me in the right direction that would be amazing

**Comment by dlarrick** [comment]
Look for the KumoCloud Technical Operation Manual. The installer pin is in there, maybe also some other info on the available options.

**Comment by omriasta** [comment]
One other option is to write an automation that will change the modes on the Mitsubishi according to readings from the external sensor. Basically you can turn it off or even adjust the target temp when certain temperatures are reached. There are a few templates like this in the home assistant boards

**Comment by dlarrick** [comment]
Closing some old tickets. This issue is more of a support discussion than an actual problem.
