### ISSUE TITLE
Celsius vs Fahrenheit 

### ISSUE THREAD

**Issue by K1DBO** [dlarrick/hass-kumo#79]
My system is set up to display in Fahrenheit but pykumo seems to be expecting Celsius.  If I display a thermostat for one of my units in Lovelace and adjust the set point, the Kumo Cloud app on my phone displays -- for the unit's setpoint.  But, if I use the climate.set_temperature service with the temperature set to 20, Lovelace will display "20 Heating" for a second or two then switch to "68 Heating".  The Kumo Cloud phone app eventually catches up too.

So there seem to be some conversions missing somewhere but I'm not sure where.  I'm also using the climate entities from the ElkM1G integration.  All values there are in Fahrenheit.  I'd expected all temperature values to be converted to a standard unit on the way in and converted again for display on the way out.  I've looked through the code for both the elk and kumo integrations but dont see any unit conversions going on anywhere in either. Am I just missing the magic (new guy here), or is something broken?

--Don

**Comment by dlarrick** [comment]
See https://github.com/dlarrick/pykumo/issues/15 for discussion.

**Comment by dlarrick** [comment]
Closing some old tickets. PyKumo expects all values in Celsius, like the units' own API does. All unit conversion is handled by Home Assistant core code.
