### ISSUE TITLE
Partial unit dropouts

### ISSUE THREAD

**Issue by Friend-Or-F0H** [dlarrick/hass-kumo#80]
I'm running into an issue where 2/5 units are periodically dropping out and coming back online. I have cleared the json cache, reinstalled the integration, and even reprovisioned the unit ip's (on my network, not just setting the ip settings in the integration). It is consistently the same 2 units on the network, and occasionally a 3rd unit will drop offline.

Log report only indicates api timeout issuing request.

Error Log below:

This error originated from a custom integration.

Logger: custom_components.kumo.climate
Source: custom_components/kumo/climate.py:136
Integration: Kumo (documentation)
First occurred: April 28, 2022, 4:40:21 PM (14 occurrences)
Last logged: April 29, 2022, 11:02:12 PM

Kumo could not set up any indoor units (try 4 of 10)
Kumo could not set up any indoor units (try 5 of 10)
Kumo could not set up any indoor units (try 6 of 10)
Kumo could not set up any indoor units (try 7 of 10)
Kumo could not set up any indoor units (try 8 of 10)

**Comment by dlarrick** [comment]
Closing some old tickets. This issue is very likely to be WiFi signal strength at the indoor unit(s) in question. Re-positioning the WiFi module inside the unit can help dramatically in my experience.
