### ISSUE TITLE
Can't install? Integration not currently available in Home Assistant?

### ISSUE THREAD

**Issue by methnen** [dlarrick/hass-kumo#88]
I can't even find the integration available in Home Assistant. 

Has it been removed?

**Comment by dlarrick** [comment]
You're not the first person to get tripped up by this. I've updated the README [Installation](https://github.com/dlarrick/hass-kumo/blob/master/README.md#installation) section to add a note that it's not directly in Home Assistant, but rather, available thru HACS, which you'll need to install first following the link I added.
