### ISSUE TITLE
Target Temp Not visible in history view

### ISSUE THREAD

**Issue by kramttocs** [dlarrick/hass-kumo#92]
It appears that it only shows if I change the temp. Otherwise I can't see the line for it.

**Comment by jhuang0** [comment]
I'm 90% your issue is with Home Assistant itself and not this integration. If you want to track the history target temperature, create a template sensor and tie it to the target temperature.

**Comment by kramttocs** [comment]
If I open a climate entity for another non-kumo thermostat and then go to history, I see the purple line across the table. For the kumo ones I don't. Maybe it's HA but doesn't seem that way yet.

Do you see the line?

**Comment by dlarrick** [comment]
I do see the target temperature in the history on my Kumo units:
![image](https://user-images.githubusercontent.com/11030293/201478532-9c32a90f-20a1-4093-aea0-77f9b22f34a5.png)

**Comment by kramttocs** [comment]
Nailed it! Mine was at the bottom and I was just missing it. Good grief :) Thank you
