### ISSUE TITLE
Error inputting timeouts in the UI

### ISSUE THREAD

**Issue by itbedguy** [dlarrick/hass-kumo#99]
I have tried to remove Kumo integration and reinstall it.  The setup seems to go through fine but the entities are showing unavailable (I have 2 units).  

There are several errors in the log file.  Primarily Timeout issuing request http:/192.168.1.38/HTTPConnection Pool....Max Retries exceed with Url:/api?M=xxxxxx

Connection timeout is set to the default of 1.2.  If I try to change that in the UI card, (Configure->Timeouts->Connection Timeout) it says "User input malformed: expected str for dictionary value @ data['response_timeout']". Tried to change it to 2.0.  Even if I type in 1.2 it throws the same error.

Any help in troubleshooting is greatly appreciated.  I tried the "Refresh" from the installer option as well on the Kumo app.

**Comment by dlarrick** [comment]
In a quick test this morning, Kumo [v0.3.3-beta](https://github.com/dlarrick/hass-kumo/releases/tag/v0.3.3-beta) is working for me with HA 2023.1.1. So either the Kumo beta fixed whatever incompatibility, or the 2023.1.1 release fixed something., or you're having some other trouble.

You can install beta components in HACS -- find Kumo in the Integrations list within the HACS UI (not the main Settings page), click it, and choose "Reinstall" from the 3-dot menu on upper right. Slide the checkbox allowing it to show beta versions.

**Comment by itbedguy** [comment]
Thanks.  I actually did update to the Beta after I sent this message and it still wasn't working.  However, I just checked it after letting it "sit" over night and now they are communicating so it must be some sort of delay.  I really appreciate the prompt response to my request for help.

Take care

**Comment by itbedguy** [comment]
One quick comment:  I still receive the error if I tried to change the time outs of using the UI card:

User input malformed: expected str for dictionary value @ data['connect_timeout']

Not a big deal for me as it works now.

FYI

**Comment by dlarrick** [comment]
I now suspect what you experienced is an outage of Mitsubishi's Kumo Cloud service. The "prefer cache" setting will isolate your installation from such outages, so long as your indoor units have a consistent IP address.

I'm keeping this issue open (and changing the title) for the "timeouts" problem.
